apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: irynanak/monitoring-client:latest
          ports:
            - containerPort: 8080
          env:
            - name: VITE_BE_URL
              value: {{ .Values.backendTargetEnv | quote }}
            - name: VITE_EXTERNAL_BE_URL
              value: {{ .Values.externalBackendTargetEnv | quote }}
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
